### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Remixful** [MickeyUK/smash-soda#3]
Is it possible to have multiple players controlling one controller? I need a feature like hotseat for the Worms game but the way the turns are managed, it's just easier to have all players share the same controller.
I was able to achieve this on RetroArch by mapping all controllers to the same port, but I couldn't find any way to do this outside of RetroArch. 
Please?

**Comment by MickeyUK** [comment]
Sure, I'll implement something like that...I love the Worms games :D

**Comment by pewqp** [comment]
hi, can you add something in audio tab that able us to choose what people in the room can hear.
for example 
I am streaming a game and talking in a discord call with my friend at the same time, but I dont want to let parsec people hear my discord
thanks in advance ;3
